#!/usr/bin/env python
#
# Proxy app for Scratch2 Raspberry PI GPIO extension
#
# Author: CoderDojo Baarn
# Copyright: Copyright 2016, CoderDojo Baarn
# License: MIT
#
import sys
import requests
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Proxy app for Scratch2 Raspberry PI GPIO extension'

@app.route('/reset_all')
def reset_all():
    r = requests.get('{0}/reset_all'.format(sys.argv[1]))
    return r.text

@app.route('/poll')
def poll():
    r = requests.get('{0}/poll'.format(sys.argv[1]))
    return r.text

@app.route('/gpio/<int:channel>/<output>')
def output(channel, output):
    r = requests.get('{0}/gpio/{1}/{2}'.format(sys.argv[1], channel, output))
    return r.text

@app.route('/mode/<int:channel>/<mode>')
def mode(channel, mode):
    r = requests.get('{0}/mode/{1}/{2}'.format(sys.argv[1], channel, mode))
    return r.text


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print 'Usage: {0} http://rpi.running.helper.app.com:5000'.format(sys.argv[0])
        sys.exit()
    app.run()
